language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ng1-generate' ]; then cd .. && eval "mv $currentfolder generator-ng1-generate" && cd generator-ng1-generate; fi

